package com.codingwithnish;

import java.util.Scanner;
import java.util.Random;

public class Game {


    public int startGame() {
        Scanner scanner = new Scanner(System.in);

        //start game
        System.out.println("Please enter your name:");
        String name = scanner.nextLine();
        System.out.println("Hello " + name + "! welcome to 'Rock, Paper, Scissors!!");

        //create a variable to hold the user response using the Scanner object. The response needs to be an integer between 1-3 (1 = Rock, 2 = Paper, 3 = Scissors)
        System.out.println("Please select Rock(1), Paper(2) or Scissors(3):");
        int selection = scanner.nextInt();
        // create a variable to hold the cpu response generated by the getCPUResponse() method.
        int computerChoice = getCPUResponse();
        //compare user and cpu response with each other to decide the winner.
        if (computerChoice==1){
            if (selection==1){
                System.out.println("It's a draw.");
            }else if(selection==2){
                System.out.println("You won! :)");
            }else{
                System.out.println("You lost. :(");
            }
        }else if (computerChoice==2){
            if (selection==1){
                System.out.println("You lost. :(");
            }else if(selection==2){
                System.out.println("It's a draw.");
            }else{
                System.out.println("You won! :)");
            }
        }else{
            if (selection==1){
                System.out.println("You won! :)");
            }else if(selection==2){
                System.out.println("You lost. :(");
            }else{
                System.out.println("It's a draw.");
            }
        }
        return 0;
      }



    public int getCPUResponse() {
        // Generate random integers in range 1 to 3
        Random rand = new Random();
        int upperbound = 4;
        int int_random = rand.nextInt(upperbound);
        return int_random;
    }
}

